version: 1.3.8
cache: true
registration:
  socialLogins: []
endpoints:
  custom:
    - name: Hybrydowy Psycholog
      apiKey: dummy
      baseURL: http://therapist:8080/v1
      models:
        default: ["hybrid-therapist"]
        fetch: false
      titleConvo: true
      titleModel: hybrid-therapist
      modelDisplayLabel: "Psycholog AI"
      addParams:
        user:
          default: "librechat_user"
      dropParams:
        - temperature
        - top_p
        - frequency_penalty
        - presence_penalty
