<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HybridTherapist.Integration" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../HybridTherapist.Application/HybridTherapist.Application.csproj" />
    <ProjectReference Include="../HybridTherapist.Domain/HybridTherapist.Domain.csproj" />
    <ProjectReference Include="../HybridTherapist.Infrastructure/HybridTherapist.Infrastructure.csproj" />
    <ProjectReference Include="../HybridTherapist.Security/HybridTherapist.Security.csproj" />
  </ItemGroup>
</Project>
